version: '3.3'
services:
  web:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm start
    ports:
      - "6006:6006"
    environment:
      NODE_ENV: production
      DEBUG: andrewangelle-site:*