[build]
  functions = "/.netlify/functions-internal"
  publish = "dist"

[dev]
  functions = "/.netlify/functions-internal"
  publish = "dist"
  port = 3000

# [[redirects]]
#   from = "/*"
#   functions = "/.netlify/functions-internal/server"
#   status = 200
