/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ColorsImport } from './routes/colors'
import { Route as IndexImport } from './routes/index'
import { Route as TypeVersionImport } from './routes/$type.$version'

// Create/Update Routes

const ColorsRoute = ColorsImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TypeVersionRoute = TypeVersionImport.update({
  id: '/$type/$version',
  path: '/$type/$version',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsImport
      parentRoute: typeof rootRoute
    }
    '/$type/$version': {
      id: '/$type/$version'
      path: '/$type/$version'
      fullPath: '/$type/$version'
      preLoaderRoute: typeof TypeVersionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/$type/$version': typeof TypeVersionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/$type/$version': typeof TypeVersionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/$type/$version': typeof TypeVersionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colors' | '/$type/$version'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colors' | '/$type/$version'
  id: '__root__' | '/' | '/colors' | '/$type/$version'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorsRoute: typeof ColorsRoute
  TypeVersionRoute: typeof TypeVersionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorsRoute: ColorsRoute,
  TypeVersionRoute: TypeVersionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/colors",
        "/$type/$version"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/colors": {
      "filePath": "colors.tsx"
    },
    "/$type/$version": {
      "filePath": "$type.$version.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
