/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as ApiResumePdfRouteImport } from './../../src/routes/api.resume.pdf'

// Create/Update Routes

const rootRoute = createServerRoute()

const ApiResumePdfRoute = ApiResumePdfRouteImport.update({
  id: '/api/resume/pdf',
  path: '/api/resume/pdf',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/api/resume/pdf': {
      id: '/api/resume/pdf'
      path: '/api/resume/pdf'
      fullPath: '/api/resume/pdf'
      preLoaderRoute: typeof ApiResumePdfRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/api.resume.pdf' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/resume/pdf']['parentRoute'],
    FileRoutesByPath['/api/resume/pdf']['id'],
    FileRoutesByPath['/api/resume/pdf']['path'],
    FileRoutesByPath['/api/resume/pdf']['fullPath'],
    unknown
  >
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/api/resume/pdf': typeof ApiResumePdfRoute
}

export interface FileRoutesByTo {
  '/api/resume/pdf': typeof ApiResumePdfRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/api/resume/pdf': typeof ApiResumePdfRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/resume/pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/resume/pdf'
  id: '__root__' | '/api/resume/pdf'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ApiResumePdfRoute: typeof ApiResumePdfRoute
}

const rootRouteChildren: RootRouteChildren = {
  ApiResumePdfRoute: ApiResumePdfRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/api/resume/pdf"
      ]
    },
    "/api/resume/pdf": {
      "filePath": "api.resume.pdf.ts"
    }
  }
}
ROUTE_MANIFEST_END */
